version: "3.9"

services:
    app:
        container_name: react_nginx_app
        image: react_nginx_app
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
           - "8070:8070"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./static:/usr/share/nginx/html
        
# volumes:
#     nginx_data:
#       driver: local
#     #   driver_opts:
#     #     o: bind
#     #     device: /volumes/nginx/data